#!/usr/bin/env bash 
# This script renames the multiples of 3 and 5
number1=3
number2=5
range=100
i=1
while ((i <= range))
do
    if (( i % number1 == 0)) && ((i % number2 == 0))
    then
	echo "fizzbuzz"
    elif (( i % number1 ==0))
    then 
	echo "fizz"
    elif ((i % number2 ==0))
    then 
	echo "buzz"
    fi
    ((i++))
done
