#!/usr/bin/env bash
# This ia a script that reads and displays the content of the file /etc/passwd with a fictional story based on the user information:
while IFS=":" read -r username _ userid groupid _ _ homedir shell
do
    user_info=$(grep "^${username}:" /etc/passwd)
    passcode=$(grep "^${username}:" /etc/shadow | cut -d':' -f2)

    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell."
    echo "User ID's place is protected by the passcode $passcode, more info about the user here: $user_info"
done < "/etc/passwd"

