#!/usr/bin/env bash
# This is a script that displays numbers 1-20 but the 4th 9th and 17th iteration display different things

counter=1
while [ $counter -le 20 ]; do
case $counter in
    4)
      echo -e "$counter:\nbad luck from China"
      ;;
    9)
      echo -e "$counter:\nbad luck from Japan"
      ;;
    17)
      echo -e "$counter:\nbad luck from Italy"
      ;;
    *)
      echo $counter
      ;;
  esac

  ((counter++))
done 
