#!/usr/bin/env bash
# This is a script that displays numbers 1-20 but the 4th 9th and 17th iteration display different things
count=1
while [ $count -le 20 ]; do
case $count in
     4)
       echo "bad luck from China"
	;;
     9)
	echo "bad luck from Japan"
	;;
     17)
	echo "bad luck from Italy" 
	;;
      *)
        echo "$count"	      
esac
   count=$((count + 1))
done 
