#!/usr/bin/env bash
# This script displays 12 hours and it's minutes
hour=0
minute=1
while [ $hours -lt 13 ]; do
  echo "$hours:$minutes"
  
  minutes=$((minutes + 1))
  if [ $minutes -eq 60 ]; then
    hours=$((hours + 1))
    minutes=0
  fi
done
