#!/usr/bin/env bash
# This script displays 12 hours and it's minutes
hour=o
minutes=1
while [ "$hours" -le 12 ]; do
	echo "Hour: $hour"
  while [ $minutes -le 59 ]; do
	  echo "$minutes"

    ((minutes++))
  done
  ((hours++))
  minutes=1
done
